title: "Machine Learning 601"
author: Nik Kim
email: knocknocknik@gmail.com
baseurl:
url: "https://nik-pitts.github.io/machinelearning601"
description: "Little Cooperative Machines ML Research Log"
favicon: /favicon.svg

permalink: /:slug.html

# Theme settings
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "Back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted

# Excerpt settings
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
